name: Novum
main: com.adamdoesthings.Novum.Novum
version: 1.3.1
api-version: 1.19
commands:
  novum:
    description: Allows players to perform rituals that alter enchanted items in exchange for some sacrifice.
    usage: /novum